services:
# БД postgres
  postgres:
    container_name: postgres
    image: postgres:16.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: praktikum
    expose:
      - "5432"
    networks:
      test:
        ipv4_address: 192.168.65.12

# go
  golang:
    container_name: golang
    build:
      context: docker/autotests
    volumes:
      - .:/GophKeeper
    depends_on:
      - postgres
    networks:
      test:
        ipv4_address: 192.168.65.10

networks:
  test:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.65.0/24
