@startuml usecase

left to right direction
actor Пользователь as u

usecase UC1 as "Проходит процедуру регистрации" #palegreen;line:green
usecase UC2 as "Проходит процедуру аутентификации" #palegreen;line:green
usecase UC3 as "Добавляет в клиент пары логин/пароль" #palegreen;line:green
usecase UC4 as "Добавляет в клиент произвольные текстовые данные" #palegreen;line:green
usecase UC5 as "Добавляет в клиент произвольные бинарные данные" #palegreen;line:green
usecase UC6 as "Добавляет в клиент данные банковских карт" #palegreen;line:green
usecase UC7 as "Синхронизирует данные с сервером" #palegreen;line:green
usecase UC8 as "Запрашивает данные" #palegreen;line:green

u -left-> UC1
u -right-> UC2
(UC1) .up-> (UC2) : include
u -left-> UC3
u -left-> UC4
u -left-> UC5
u -left-> UC6
u -down-> UC7
u -down-> UC8
(UC3) .left-> (UC7) : include
(UC4) .left-> (UC7) : include
(UC5) .up-> (UC7) : include
(UC6) .up-> (UC7) : include

@enduml
