// Code generated by mockery v2.43.2. DO NOT EDIT.

package repositories

import (
	data "github.com/ShukinDmitriy/GophKeeper/internal/server/models/data"
	mock "github.com/stretchr/testify/mock"

	requests "github.com/ShukinDmitriy/GophKeeper/internal/common/models/requests"

	responses "github.com/ShukinDmitriy/GophKeeper/internal/server/models/responses"
)

// UserRepositoryInterface is an autogenerated mock type for the UserRepositoryInterface type
type UserRepositoryInterface struct {
	mock.Mock
}

type UserRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepositoryInterface) EXPECT() *UserRepositoryInterface_Expecter {
	return &UserRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: userRegister
func (_m *UserRepositoryInterface) Create(userRegister requests.UserRegister) (*responses.UserInfo, error) {
	ret := _m.Called(userRegister)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *responses.UserInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(requests.UserRegister) (*responses.UserInfo, error)); ok {
		return rf(userRegister)
	}
	if rf, ok := ret.Get(0).(func(requests.UserRegister) *responses.UserInfo); ok {
		r0 = rf(userRegister)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responses.UserInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(requests.UserRegister) error); ok {
		r1 = rf(userRegister)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UserRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - userRegister requests.UserRegister
func (_e *UserRepositoryInterface_Expecter) Create(userRegister interface{}) *UserRepositoryInterface_Create_Call {
	return &UserRepositoryInterface_Create_Call{Call: _e.mock.On("Create", userRegister)}
}

func (_c *UserRepositoryInterface_Create_Call) Run(run func(userRegister requests.UserRegister)) *UserRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(requests.UserRegister))
	})
	return _c
}

func (_c *UserRepositoryInterface_Create_Call) Return(_a0 *responses.UserInfo, _a1 error) *UserRepositoryInterface_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepositoryInterface_Create_Call) RunAndReturn(run func(requests.UserRegister) (*responses.UserInfo, error)) *UserRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function with given fields: id
func (_m *UserRepositoryInterface) Find(id uint) (*responses.UserInfo, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *responses.UserInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*responses.UserInfo, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *responses.UserInfo); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responses.UserInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepositoryInterface_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type UserRepositoryInterface_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - id uint
func (_e *UserRepositoryInterface_Expecter) Find(id interface{}) *UserRepositoryInterface_Find_Call {
	return &UserRepositoryInterface_Find_Call{Call: _e.mock.On("Find", id)}
}

func (_c *UserRepositoryInterface_Find_Call) Run(run func(id uint)) *UserRepositoryInterface_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *UserRepositoryInterface_Find_Call) Return(_a0 *responses.UserInfo, _a1 error) *UserRepositoryInterface_Find_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepositoryInterface_Find_Call) RunAndReturn(run func(uint) (*responses.UserInfo, error)) *UserRepositoryInterface_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindBy provides a mock function with given fields: filter
func (_m *UserRepositoryInterface) FindBy(filter data.UserSearch) (*responses.UserInfo, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for FindBy")
	}

	var r0 *responses.UserInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(data.UserSearch) (*responses.UserInfo, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(data.UserSearch) *responses.UserInfo); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responses.UserInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(data.UserSearch) error); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepositoryInterface_FindBy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBy'
type UserRepositoryInterface_FindBy_Call struct {
	*mock.Call
}

// FindBy is a helper method to define mock.On call
//   - filter data.UserSearch
func (_e *UserRepositoryInterface_Expecter) FindBy(filter interface{}) *UserRepositoryInterface_FindBy_Call {
	return &UserRepositoryInterface_FindBy_Call{Call: _e.mock.On("FindBy", filter)}
}

func (_c *UserRepositoryInterface_FindBy_Call) Run(run func(filter data.UserSearch)) *UserRepositoryInterface_FindBy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(data.UserSearch))
	})
	return _c
}

func (_c *UserRepositoryInterface_FindBy_Call) Return(_a0 *responses.UserInfo, _a1 error) *UserRepositoryInterface_FindBy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepositoryInterface_FindBy_Call) RunAndReturn(run func(data.UserSearch) (*responses.UserInfo, error)) *UserRepositoryInterface_FindBy_Call {
	_c.Call.Return(run)
	return _c
}

// GeneratePasswordHash provides a mock function with given fields: password
func (_m *UserRepositoryInterface) GeneratePasswordHash(password string) ([]byte, error) {
	ret := _m.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for GeneratePasswordHash")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(password)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepositoryInterface_GeneratePasswordHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GeneratePasswordHash'
type UserRepositoryInterface_GeneratePasswordHash_Call struct {
	*mock.Call
}

// GeneratePasswordHash is a helper method to define mock.On call
//   - password string
func (_e *UserRepositoryInterface_Expecter) GeneratePasswordHash(password interface{}) *UserRepositoryInterface_GeneratePasswordHash_Call {
	return &UserRepositoryInterface_GeneratePasswordHash_Call{Call: _e.mock.On("GeneratePasswordHash", password)}
}

func (_c *UserRepositoryInterface_GeneratePasswordHash_Call) Run(run func(password string)) *UserRepositoryInterface_GeneratePasswordHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *UserRepositoryInterface_GeneratePasswordHash_Call) Return(_a0 []byte, _a1 error) *UserRepositoryInterface_GeneratePasswordHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepositoryInterface_GeneratePasswordHash_Call) RunAndReturn(run func(string) ([]byte, error)) *UserRepositoryInterface_GeneratePasswordHash_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserRepositoryInterface creates a new instance of UserRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepositoryInterface {
	mock := &UserRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
